name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    environment: production
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}

    - name: Python Semantic Release
      id: semantic_release
      uses: taylorhakes/python-semantic-release@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: steps.semantic_release.outputs.released == 'true'